#!/bin/bash

par=$1
resolv_file='/etc/resolv.conf'
interfaces_file='/etc/network/interfaces'

if [[ $par = WHONIX ]]; then
    echo "Change settings for WHONIX"
    #/etc/network/interfaces
    echo "# This file describes the network interfaces available on your system" > $interfaces_file
    echo "# and how to activate them. For more information, see interfaces(5). " >> $interfaces_file
    echo "" >> $interfaces_file
    echo "source /etc/network/interfaces.d/*" >> $interfaces_file
    echo "" >> $interfaces_file
    echo "# The loopback network interface" >> $interfaces_file
    echo "auto eth0" >> $interfaces_file
    echo "iface lo inet loopback" >> $interfaces_file
    echo "iface eth0 inet static" >> $interfaces_file
    echo "address 10.152.152.11" >> $interfaces_file
    echo "netmask 255.255.192.0" >> $interfaces_file
    echo "gateway 10.152.152.10" >> $interfaces_file
    #/etc/resolv.conf
    echo "# Generated by NetworkManager" > $resolv_file
    echo "nameserver 10.152.152.10" >> $resolv_file
    echo "You are using WHONIX"

elif [ $par = NAT ]; then
    echo "Change settings for NAT"
    #/etc/network/interfaces
    echo "# This file describes the network interfaces available on your system" > $interfaces_file
    echo "# and how to activate them. For more information, see interfaces(5). " >> $interfaces_file
    echo "" >> $interfaces_file
    echo "source /etc/network/interfaces.d/*" >> $interfaces_file
    echo "" >> $interfaces_file
    echo "# The loopback network interface" >> $interfaces_file
    echo "auto eth0" >> $interfaces_file
    echo "iface lo inet loopback" >> $interfaces_file
    #/etc/resolv.conf
    echo "# Generated by NetworkManager" > $resolv_file
    echo "nameserver 1.1.1.1" >> $resolv_file
    echo "nameserver 1.0.0.1" >> $resolv_file
    echo "nameserver 8.8.4.4" >> $resolv_file
    echo "nameserver 8.8.8.8" >> $resolv_file
    echo "WHONIX is Off. You are using NAT"

else
    echo "Try using parameters NAT or WHONIX"

fi
